# environment: local, dev, prod
env: "local"

token_ttl: 1h

grpc:
  port: 44044
  timeout: 10h

database:
  type: "sqlite"
  path: "./storage/sso.db"
  host: "localhost"
  port: 5432
  username: "admin"
  password: "admin"
  database: "sso"
  ssl_mode: "disable"